export const SET_CHARACTERS = 'SET_CHARACTERS'
export const FETCH_CHARACTERS = 'FETCH_CHARACTERS'

export const SET_ONE_CHARACTER = 'SET_ONE_CHARACTER'
export const FETCH_ONE_CHARACTER = 'FETCH_ONE_CHARACTER'